src/CatBundle/Entity/Medal.php
<?php

namespace CatBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="CatBundle\Repository\MedalRepository")
 * @ORM\Table(name="medal")
 * @Vich\Uploadable
 */
class Medal extends AbstractProduct
{
    public function getClassForFront()
    {
        return 'Médailles';
    }
    public function getSanitizeName()
    {
        return 'medal';
    }
    public function getImageRepository(){
        return 'medal_images';
    }

    /**
     * @ORM\Column(type="integer", name="annee", nullable=true)
     */
    private $annee;

    /**
     * @ORM\Column(type="decimal", scale=2, name="purchasePrice", nullable=true)
     */
    private $purchasePrice;

    /**
     * @ORM\Column(type="decimal", scale=2, name="sellingPrice", nullable=true)
     */
    private $sellingPrice;

    /**
     * @Vich\UploadableField(mapping="medal_images", fileNameProperty="image", nullable=true)
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="date", name="updatedAt")
     */
    private $updatedAt;

    function __construct()
    {
        parent::__construct();
        $this->purchasePrice = 2;
        $this->sellingPrice  = null;
        $this->imageFile     = null;
        $this->annee         = null;
        $this->updatedAt     = new \DateTime('now');;
    }

    /**
     * @param $sellingPrice
     * @return $this
     */
    public function setSellingPrice($sellingPrice)
    {
        $this->sellingPrice = $sellingPrice;
        return $this;
    }

    /**
     * Get sellingPrice
     *
     * @return string
     */
    public function getSellingPrice()
    {
        return $this->sellingPrice;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param $updatedAt
     * @return $this
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get purchaseDate
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @return mixed
     */
    public function getAnnee()
    {
        return $this->annee;
    }

    /**
     * @param $annee
     * @return $this
     */
    public function setAnnee($annee)
    {
        $this->annee = $annee;
        return $this;
    }
}

src/CatBundle/Resources/views/Mosaic/mosaicproduct.html.twig
{% block mosaic_product %}
    {% if products|length == 0 %}
        <h3>Liste vide</h3>
    {% endif %}
    <div id="mosaic-grid" class="mosaic-grid row">
        {% for product in products %}
            <div class="img col-xs-6 col-sm-4 col-md-2 col-lg-2">
                <a href="{{ asset(getImageLink(product, 'productfull')) }}"
                   title="{{ product.name }}
                    {% if desc is defined %}
                        {% for variable, parametre in desc %}
                            {% if parametre.prefixe is defined %}{{ parametre.prefixe }}{% endif %}
                            {{ attribute(product, variable) }}
                            {% if parametre.suffixe is defined %}{{ parametre.suffixe }}{% endif %}
                        {% endfor %}
                    {% endif %}"
                   class="img-popup-mosaic">

                    <div class="miniatureProduct"
                         data-src-s="{{ asset(getImageLink(product, 'productminiature_s')) }}"
                         data-height-s="162"
                         data-src-m="{{ asset(getImageLink(product, 'productminiature_m')) }}"
                         data-height-m="173"
                         data-src-l="{{ asset(getImageLink(product, 'productminiature_l')) }}"
                         data-height-l="176"
                         data-src-xl="{{ asset(getImageLink(product, 'productminiature_xl')) }}"
                         data-height-xl="216"
                         data-src-xxl="{{ asset(getImageLink(product, 'productminiature_xxl')) }}"
                         data-height-xxl="285"
                    ></div>
                </a>
                <div class="desc">{{ product.name }}
                {% if desc is defined %}
                    {% for variable, parametre in desc %}
                        {% if parametre.prefixe is defined %}{{ parametre.prefixe }}{% endif %}
                        {{ attribute(product, variable) }}
                        {% if parametre.suffixe is defined %}{{ parametre.suffixe }}{% endif %}
                    {% endfor %}
                {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/CatBundle/Resources/views/Mosaic/mosaictag.html.twig
{% block mosaic_tag %}
    <div id="mosaic-grid" class="mosaic-grid row">
        {% for tag in tags %}
            <div class="img col-xs-6 col-sm-4 col-md-2 col-lg-2">
                <a href="{{ group_pages.collection.route }}/{{ getRouteProduct(tag.products|first) }}/{{ (tag.sanitizeName) }}">
                    {{ tag.label|capitalize  }}
                    {% set product = tag.products|last %}
                    <div class="miniatureProduct"
                         data-src-s="{{ asset(getImageLink(product, 'productminiature_s')) }}"
                         data-height-s="162"
                         data-src-m="{{ asset(getImageLink(product, 'productminiature_m')) }}"
                         data-height-m="173"
                         data-src-l="{{ asset(getImageLink(product, 'productminiature_l')) }}"
                         data-height-l="176"
                         data-src-xl="{{ asset(getImageLink(product, 'productminiature_xl')) }}"
                         data-height-xl="216"
                         data-src-xxl="{{ asset(getImageLink(product, 'productminiature_xxl')) }}"
                         data-height-xxl="285"
                            ></div>
                    {% set numberProducts = 0 %}
                    {% for oneTotal in total %}
                        {% if oneTotal.label ==  tag.label %}
                            {% set numberProducts = oneTotal[1] %}
                        {% endif %}
                    {% endfor %}
                </a>
                <div class="desc">{{ numberProducts }} {{ getTypeProduct(tag.products|first) }}</div>
            </div>
        {% endfor %}
    </div>
{% endblock %}